//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.AsignacionCredito = new HashSet<AsignacionCredito>();
            this.PtoVenta = new HashSet<PtoVenta>();
            this.Despacho = new HashSet<Despacho>();
            this.Factura = new HashSet<Factura>();
            this.PromocionCliente = new HashSet<PromocionCliente>();
        }
    
        public decimal idCliente { get; set; }
        public string identificacion { get; set; }
        public Nullable<decimal> idTipoIdentificacion { get; set; }
        public Nullable<decimal> cupo { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string nuevo { get; set; }
        public string email { get; set; }
        public Nullable<decimal> codintCliente { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string usaurioreg { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string usaurio_act { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> FueEnviado { get; set; }
        public Nullable<decimal> DiasCredito { get; set; }
        public string env_contabilidad { get; set; }
        public Nullable<bool> env_noti_Email { get; set; }
        public Nullable<bool> envi_noti_SMS { get; set; }
        public Nullable<bool> env_noti_Whatsapp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCredito> AsignacionCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtoVenta> PtoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despacho> Despacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromocionCliente> PromocionCliente { get; set; }
    }
}
