//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupones
    {
        public decimal idPromocion { get; set; }
        public decimal idCupones { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaSorteo { get; set; }
        public string usuarioreg { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public Nullable<decimal> idFactura { get; set; }
        public string imprimir { get; set; }
        public string impresora { get; set; }
        public Nullable<decimal> VecesImpreso { get; set; }
        public Nullable<decimal> idEstado { get; set; }
    }
}
