//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        public decimal idDespacho { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public Nullable<decimal> idFormaPago { get; set; }
        public Nullable<decimal> idIVA { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> MontoSIMP { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public Nullable<decimal> Subsidio { get; set; }
        public Nullable<decimal> MontoDolares { get; set; }
        public string unidadMedida { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> idProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<bool> caneca { get; set; }
        public string TipoVenta { get; set; }
        public string Dispensador { get; set; }
        public string PuntoCarga { get; set; }
        public string Manguera { get; set; }
        public Nullable<System.DateTime> FechaTransactor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Transaccion { get; set; }
        public Nullable<decimal> idFactura { get; set; }
        public Nullable<decimal> idusuadio { get; set; }
        public string usuario { get; set; }
        public string nombreVendedor { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public string placa { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> kilometraje { get; set; }
        public string Imprimir { get; set; }
        public string Impresora { get; set; }
        public string env_contabilidad { get; set; }
        public Nullable<bool> env_factind { get; set; }
        public Nullable<decimal> idTurno { get; set; }
        public Nullable<decimal> kardexStock { get; set; }
        public Nullable<int> fechaentero { get; set; }
    
        public virtual AperturaCierreTurno AperturaCierreTurno { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
