//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAperturaCierre
    {
        public decimal idTurno { get; set; }
        public decimal idDetalle { get; set; }
        public Nullable<decimal> idDispensador { get; set; }
        public Nullable<decimal> idPuntoCarga { get; set; }
        public Nullable<decimal> idManguera { get; set; }
        public string Producto { get; set; }
        public string Manguera { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Mecanico { get; set; }
    
        public virtual AperturaCierreTurno AperturaCierreTurno { get; set; }
    }
}
