//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMA_PAGO()
        {
            this.PtoVenta = new HashSet<PtoVenta>();
            this.TotalTurnoFormaPago = new HashSet<TotalTurnoFormaPago>();
        }
    
        public decimal idFormaPago { get; set; }
        public string DESCRIPCION { get; set; }
        public string Alias { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public string CodigoSRI { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string Imprimir { get; set; }
        public string PuedeFacturar { get; set; }
        public string TipoVenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtoVenta> PtoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalTurnoFormaPago> TotalTurnoFormaPago { get; set; }
    }
}
