//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVA_Configurado
    {
        public decimal idIVA { get; set; }
        public string IVA { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public Nullable<System.DateTime> FECHA_REG { get; set; }
        public string USUARIO_REG { get; set; }
    }
}
