//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRANSACTOR_BASEEntities : DbContext
    {
        public TRANSACTOR_BASEEntities()
            : base("name=TRANSACTOR_BASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ambiente> Ambiente { get; set; }
        public virtual DbSet<AperturaCierreTurno> AperturaCierreTurno { get; set; }
        public virtual DbSet<AsignacionCredito> AsignacionCredito { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ClientePlaca> ClientePlaca { get; set; }
        public virtual DbSet<Cupones> Cupones { get; set; }
        public virtual DbSet<Deposito> Deposito { get; set; }
        public virtual DbSet<Despacho> Despacho { get; set; }
        public virtual DbSet<DetalleAperturaCierre> DetalleAperturaCierre { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public virtual DbSet<IVA_Configurado> IVA_Configurado { get; set; }
        public virtual DbSet<PromocionCliente> PromocionCliente { get; set; }
        public virtual DbSet<Promociones> Promociones { get; set; }
        public virtual DbSet<PtoVenta> PtoVenta { get; set; }
        public virtual DbSet<SRI_IMPUESTO_IVA> SRI_IMPUESTO_IVA { get; set; }
        public virtual DbSet<TipoComprobante> TipoComprobante { get; set; }
        public virtual DbSet<TipoEmision> TipoEmision { get; set; }
        public virtual DbSet<TipoFactura> TipoFactura { get; set; }
        public virtual DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
        public virtual DbSet<TipoVenta> TipoVenta { get; set; }
        public virtual DbSet<TotalTurnoFormaPago> TotalTurnoFormaPago { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
