//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promociones
    {
        public decimal idPromocion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<bool> Acumulable { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<decimal> idEstado { get; set; }
    }
}
