//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionCliente
    {
        public decimal idCliente { get; set; }
        public decimal idPromocion { get; set; }
        public Nullable<decimal> ValorAcumulado { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
