//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtoVenta
    {
        public decimal idPtoVenta { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public string identificacion { get; set; }
        public Nullable<decimal> idTipoIdentificacion { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
        public Nullable<decimal> idFormaPago { get; set; }
        public string PuntoCarga { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> MontoDolares { get; set; }
        public string unidadMedida { get; set; }
        public Nullable<bool> caneca { get; set; }
        public string TipoVenta { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public string EstadoDocumento { get; set; }
        public Nullable<decimal> idusuadio { get; set; }
        public string usuario { get; set; }
        public string nombreVendedor { get; set; }
        public string placa { get; set; }
        public Nullable<decimal> kilometraje { get; set; }
        public string Imprimir { get; set; }
        public string Impresora { get; set; }
        public Nullable<decimal> DiasPlazo { get; set; }
        public Nullable<decimal> idTurno { get; set; }
        public string tipocliente { get; set; }
    
        public virtual AperturaCierreTurno AperturaCierreTurno { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
    }
}
