//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRI_IMPUESTO_IVA
    {
        public decimal ID_IMPUESTO_IVA { get; set; }
        public string IVA { get; set; }
        public Nullable<decimal> TARIFA { get; set; }
        public Nullable<decimal> idESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_ACT { get; set; }
        public string USUARIO_ACT { get; set; }
        public string IP { get; set; }
    }
}
