//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEmision
    {
        public decimal idTipoEmision { get; set; }
        public string descripcion { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> idEstado { get; set; }
    }
}
