//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionTxt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public decimal IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string clave { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public string email { get; set; }
        public string usuario_reg { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_act { get; set; }
        public string usuario_act { get; set; }
        public Nullable<decimal> idPerfil { get; set; }
        public string CodigoAlterno { get; set; }
    }
}
